"""Canonical enum values used on the wire and in persisted traces."""

from enum import Enum


class StrEnum(str, Enum):
    """Python 3.10 compatible string enum."""

    def __str__(self) -> str:
        return self.value


class CoordinateSystem(StrEnum):
    LPS = "LPS"
    RAS = "RAS"


class ArtifactType(StrEnum):
    CT_VOLUME = "CT_VOLUME"
    MCS_SEGMENTATION = "MCS_SEGMENTATION"
    NIFTI_LABELMAP = "NIFTI_LABELMAP"
    SEGMENTATION_MASK = "SEGMENTATION_MASK"
    SKIN_SURFACE_MASK = "SKIN_SURFACE_MASK"
    TARGET_MASK = "TARGET_MASK"
    LESION_MASK = "LESION_MASK"
    DANGER_MASK = "DANGER_MASK"
    CANDIDATE_PATH_SET = "CANDIDATE_PATH_SET"
    PATH_MASK = "PATH_MASK"
    CASE_REPORT = "CASE_REPORT"


class ArtifactStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    PENDING = "PENDING"
    INVALID = "INVALID"
    MISSING = "MISSING"


class ToolExecutionStatus(StrEnum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ErrorCode(StrEnum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    MISSING_ARTIFACT = "MISSING_ARTIFACT"
    ARTIFACT_NOT_AVAILABLE = "ARTIFACT_NOT_AVAILABLE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    GEOMETRY_MISMATCH = "GEOMETRY_MISMATCH"
    SPACING_MISMATCH = "SPACING_MISMATCH"
    DIRECTION_MISMATCH = "DIRECTION_MISMATCH"
    LABEL_SCHEMA_ERROR = "LABEL_SCHEMA_ERROR"
    REQUIRED_LABEL_MISSING = "REQUIRED_LABEL_MISSING"
    UNKNOWN_LABEL_VALUE = "UNKNOWN_LABEL_VALUE"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_VERSION_MISMATCH = "MODEL_VERSION_MISMATCH"
    MODEL_INFERENCE_FAILED = "MODEL_INFERENCE_FAILED"
    GPU_OUT_OF_MEMORY = "GPU_OUT_OF_MEMORY"
    EMPTY_SEGMENTATION = "EMPTY_SEGMENTATION"
    QUALITY_CHECK_FAILED = "QUALITY_CHECK_FAILED"
    TARGET_OUT_OF_BOUNDS = "TARGET_OUT_OF_BOUNDS"
    NO_CANDIDATE_PATH = "NO_CANDIDATE_PATH"
    NO_FEASIBLE_PATH = "NO_FEASIBLE_PATH"
    REQUIRED_DANGER_MASK_MISSING = "REQUIRED_DANGER_MASK_MISSING"
    SAFETY_CHECK_FAILED = "SAFETY_CHECK_FAILED"
    RISK_EVALUATION_FAILED = "RISK_EVALUATION_FAILED"
    SKIN_PENETRATION_UNDETERMINED = "SKIN_PENETRATION_UNDETERMINED"
    TIMEOUT = "TIMEOUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    RETRYABLE_ERROR = "RETRYABLE_ERROR"
    NON_RETRYABLE_ERROR = "NON_RETRYABLE_ERROR"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ValidationSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class InferencePrecision(StrEnum):
    FP32 = "FP32"
    FP16 = "FP16"
    INT8 = "INT8"


class SkinSurfaceMethod(StrEnum):
    EROSION_DIFFERENCE = "EROSION_DIFFERENCE"
    DISTANCE_BAND = "DISTANCE_BAND"


class AngleReference(StrEnum):
    LOCAL_SURFACE_NORMAL = "LOCAL_SURFACE_NORMAL"
    AXIAL_PLANE_NORMAL = "AXIAL_PLANE_NORMAL"
    NEEDLE_DEVICE_AXIS = "NEEDLE_DEVICE_AXIS"


class RiskStructure(StrEnum):
    BONE = "BONE"
    HEART = "HEART"
    BRONCHUS = "BRONCHUS"
    LARGE_VESSEL = "LARGE_VESSEL"
    LUNG = "LUNG"
    SKIN = "SKIN"
    OTHER = "OTHER"


class RiskLevel(StrEnum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    STOP = "STOP"
    UNKNOWN = "UNKNOWN"


class PathDisposition(StrEnum):
    ACCEPTED = "ACCEPTED"
    ACCEPTED_WITH_WARNING = "ACCEPTED_WITH_WARNING"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class PenetrationStatus(StrEnum):
    PENETRATED = "PENETRATED"
    NOT_PENETRATED = "NOT_PENETRATED"
    SUSPECTED_SLIP = "SUSPECTED_SLIP"
    UNKNOWN = "UNKNOWN"


class Connectivity(int, Enum):
    SIX = 6
    EIGHTEEN = 18
    TWENTY_SIX = 26


class RecommendedAction(StrEnum):
    CONTINUE = "CONTINUE"
    RETRY = "RETRY"
    REPLAN = "REPLAN"
    REQUEST_INPUT = "REQUEST_INPUT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    STOP = "STOP"
